name: Archive and Attach to Release for Brew Formula

on:
  release:
    types:
      - created

jobs:
  archiveAndAttach:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pyopenssl

      - name: Create and Switch to New Branch
        run: |
          git switch main

      - name: Prepend Line to File
        run: |
          echo -e "#!/usr/bin/env ruby\n$(cat resource_mover.rb)" > terraform-state-split

      - name: Create Archive
        run: tar -czvf terraform-state-split.tar.gz terraform-state-split

      - name: Upload Archive
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state-split
          path: terraform-state-split.tar.gz

      - name: Get Release ID
        id: release
        run: echo "::set-output name=id::${{ github.event.release.id }}"

      - name: Download Archive
        uses: actions/download-artifact@v2
        with:
          name: terraform-state-split
          path: temp

      - name: Attach Archive to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: temp/terraform-state-split.tar.gz
          asset_name: terraform-state-split.tar.gz
          asset_content_type: application/gzip

          
      - name: SHA256 Calculation
        id: sha256_calc
        run: |
          mkdir new_repo
          wget "https://github.com/shebang-labs/terraform-state-split/releases/download/${{ github.event.release.tag_name }}/terraform-state-split.tar.gz" -O "terraform-state-split.tar.gz"
          cp brew-formula-template.rb new_repo/terraform-state-split.rb
          TAR_FILE="terraform-state-split.tar.gz"
          
          SHA256_HASH=$(openssl dgst -sha256 "$TAR_FILE" | awk '{print $2}')
          echo "SHA256 Hash: $SHA256_HASH"
          echo "::set-output name=hash::$SHA256_HASH"
        working-directory: ${{ github.workspace }}

      - name: Copy and Replace Version Name
        run: |
          sed -i 's/version_name/${{ github.event.release.tag_name }}/g' new_repo/terraform-state-split.rb
          sed -i 's/sha256_replace/${{ steps.sha256_calc.outputs.hash }}/g' new_repo/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Clone another repository
        env:
          access_token: ${{ secrets.HOMEBREW_TAP_GH_PAT }}
        run: |
          git config --global user.name "Shebang Labs"
          git config --global user.email "hello@shebanglabs.io"
          git clone https://shebang-labs:${{ secrets.HOMEBREW_TAP_GH_PAT }}@github.com/shebang-labs/homebrew-tap.git
        working-directory: ${{ github.workspace }}
        
      - name: Replace brew-formula-template.rb in another repository
        run: |
          cp new_repo/terraform-state-split.rb homebrew-tap/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Commit and Push changes
        env:
          access_token: ${{ secrets.HOMEBREW_TAP_GH_PAT }}
        run: |
          cd homebrew-tap
          git add terraform-state-split.rb
          git commit -m "Update terraform-state-split.rb with new version"
          git push origin main
        working-directory: ${{ github.workspace }}

      - name: Clean up
        run: |
          git checkout main
          rm -rf temp terraform-state-split.tar.gz