name: Archive and Attach to Release for Brew Formula

on:
  release:
    types:
      - created

jobs:
  archiveAndAttach:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          access-token: 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

      - name: Prepend Line to File
        run: |
          echo -e "#!/usr/bin/env ruby\n$(cat resource_mover.rb)" > terraform-state-split

      - name: Create Archive
        run: tar -czvf terraform-state-split.tar.gz terraform-state-split

      - name: Upload Archive
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state-split
          path: terraform-state-split.tar.gz

      - name: Get Release ID
        id: release
        run: echo "::set-output name=id::${{ github.event.release.id }}"

      - name: Download Archive
        uses: actions/download-artifact@v2
        with:
          name: terraform-state-split
          path: temp

      - name: Attach Archive to Release
        uses: actions/upload-release-asset@v1
        with:
          access-token: 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
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: temp/terraform-state-split.tar.gz
          asset_name: terraform-state-split.tar.gz
          asset_content_type: application/gzip

      - name: Clean up
        run: rm -rf temp terraform-state-split.tar.gz
