name: Copy and Replace

on:
  release:
    types:
      - created

jobs:
  copy_and_replace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy and Replace Version Name
        run: |
          mkdir new_repo
          cp brew-formula-template.rb new_repo/terraform-state-split.rb
          sed -i 's/version_name/${{ github.event.release.tag_name }}/g' new_repo/terraform-state-split.rb
          sed -i 's/sha256_replace/${{ github.event.release.tag_name }}/g' new_repo/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Clone another repository
        env:
          access_token: ${{ secrets.HOMEBREW_TAP_GH_PAT }}
        run: |
          git config --global user.name "Shebang Labs"
          git config --global user.email "hello@shebanglabs.io"
          git clone https://shebang-labs:${{ secrets.HOMEBREW_TAP_GH_PAT }}@github.com/shebang-labs/terraform-state-split.git
        working-directory: ${{ github.workspace }}
        
      - name: Replace brew-formula-template.rb in another repository
        run: |
          cp new_repo/terraform-state-split.rb homebrew-tap/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Commit and Push changes
        env:
          access_token: ${{ secrets.HOMEBREW_TAP_GH_PAT }}
        run: |
          cd homebrew-tap
          git config user.name "Shebang Labs"
          git config user.email "hello@shebanglabs.io"
          git add terraform-state-split.rb
          git commit -m "Update terraform-state-split.rb with new version"
          git push origin main
        working-directory: ${{ github.workspace }}
