name: Copy and Replace

on:
  release:
    types:
      - created

jobs:
  copy_and_replace:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Copy and Replace Version Name
        run: |
          mkdir new_repo
          cp brew-formula-template.rb new_repo/terraform-state-split.rb
          sed -i 's/version_name/${{ github.event.release.tag_name }}/g' new_repo/terraform-state-split.rb
          sed -i 's/sha256_replace/${{ github.event.release.tag_name }}/g' new_repo/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Clone another repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git clone https://github.com/shebang-labs/homebrew-tap.git
        working-directory: ${{ github.workspace }}
        
      - name: Replace brew-formula-template.rb in another repository
        run: |
          cp new_repo/terraform-state-split.rb homebrew-tap/terraform-state-split.rb
        working-directory: ${{ github.workspace }}
        
      - name: Commit and Push changes
        run: |
          cd homebrew-tap
          git add terraform-state-split.rb
          git commit -m "Update terraform-state-split.rb with new version"
          git push
        working-directory: ${{ github.workspace }}
